spring:
  application:
    name: Admin-Server
  security:
    user:
      name: spdata
      password: spdata
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      user.name: "spdata"
      user.password: "spdata"