server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true # 将自己也注册
    fetchRegistry: true #获取注册表
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
  security:
    user:
      name: eureka
      password: eureka