spring:
  application:
    name: Admin-Server
  security:
    oauth2:
      client:
        registration:
          spdata:
            provider: spdata
            client-id: spdata
            client-secret: secret
            client-name: spdata
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: all,read
        provider:
          spdata:
            authorization-uri: http://127.0.0.1:8762/auth/oauth/authorize
            token-uri: http://127.0.0.1:8762/auth/oauth/token
            userInfoUri: http://127.0.0.1:8765/resources/user/info
#            userNameAttribute: data
server:
  port: 9000
  servlet:
    session:
      cookie:
        name: monitor-sessionID
    context-path: /monitor
eureka:
  client:
    serviceUrl:
      defaultZone: http://spdata:spdata@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      user.name: "spdata"
      user.password: "spdata"
      management.context-path: ${server.servlet.context-path}/actuator
    health-check-url-path: ${server.servlet.context-path}/actuator/health

logging:
  level:
    root: warn
    org.springframework.security: debug