logging:
  level:  # 日志级别
    com.spdata: debug
    org.springframework.security: debug
    com.alibaba.nacos.client: warn
server:
  port: 8763
  servlet:
    context-path: /admin
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spdata.common
  mapper-locations: classpath*:mapping/**/*.xml
pagehelper:
  reasonable: true
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
spring:
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://spdata:spdata@eureka-host:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet.path}/actuator
    home-page-url: ${server.servlet.path}
  #actuate 监控配置
  server:
    servlet:
      context-path: ${server.servlet.path}
#openfeign 配置
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
  threadpool:
    default:
      coreSize: 100