eureka:
  client:
    serviceUrl:
      defaultZone:  http://spdata:spdata@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: server-gateway
zuul:
  include-debug-header: true
  routes:
    server-oauth2:
      serverID: server-oauth2
      path: /auth/**
      strip-prefix: false
    server-crm:
      serverID: server-crm
      path: /admin/**
      sensitiveHeaders: null
      strip-Prefix: false #strip-Prefix 携带前缀 为true则不携带
    resource-server-oath2:
      serverID: resource-server-oath2
      path: /resources/**
      strip-prefix: false
  add-host-header: true
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods
  strip-prefix: false
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
server:
  port: 80
logging:
  level:
    root: info
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000