eureka:
  client:
    serviceUrl:
      defaultZone:  http://spdata:spdata@eureka-host:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
    health-check-url-path: ${server.servlet.context-path}/actuator/health

spring:
  application:
    name: resource-server-oath2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/webdb?serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: 712yqf
    initialSize: 5
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
server:
  port: 8765
  servlet:
    context-path: /resources
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spdata.common
  mapper-locations: classpath*:Mapper/**/*.xml
pagehelper:
  reasonable: true
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
spdata:
  autoconfig:
    enable: true
logging:
  level:
    root: info
