server:
  port: 8762
  servlet:
    context-path: /auth/
    session:
      cookie:
        name: oauth-session
logging:
  level:
    com.yangqifang: debug
    com.alibaba.nacos.client: warn
spring:
  security:
    filter:
      order: 3
  freemarker:
    template-loader-path: classpath:/template
    cache: false
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
  main:
    allow-bean-definition-overriding: true
dubbo:
  registry:
    address: nacos://47.101.32.241:8848
  application:
    name: fast-oauth2-dubbo
  protocol:
    name: dubbo