logging:
  level:
    com.yangqifang: debug
    com.alibaba.nacos.client.naming: error
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.32.241:3307/webdb?serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: yangqifang
    initialSize: 5
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.yangqifang.crm.api
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml