server:
  port: 8762
logging:
  level:
    root: info
    com.spdata.*.dao: debug
spring:
  application:
    name: server-oauth2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webdb?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 712yqf
    initialSize: 5
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
  security:
    filter:
      order: 3
    user:
      name: spdata
      password: spdata
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
mybatis:
  type-aliases-package: com.spdata.oauth2.*.entity,com.spdata.common
  mapper-locations: classpath*:mapping/*.xml,classpath*:mapping/*/*.xml
  configuration:
    mapUnderscoreToCamelCase: true