server:
  port: 8762
  servlet:
    context-path: /auth/
    session:
      cookie:
        name: oauth-session
logging:
  level:
    root: info
    com.spdata: debug
spring:
  application:
    name: server-oauth2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/webdb?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 712yqf
    initialSize: 5
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
  security:
    filter:
      order: 3
  devtools:
    livereload:
      enabled: true
    restart:
      exclude: template
  freemarker:
    template-loader-path: classpath:/template
    cache: false
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl
eureka:
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet.context-path}actuator
    health-check-url-path: ${server.servlet.context-path}/actuator/health
  client:
    serviceUrl:
      defaultZone: http://spdata:spdata@eureka-host:8761/eureka/
mybatis:
  type-aliases-package: com.spdata.oauth2.*.entity,com.spdata.common
  mapper-locations: classpath*:mapping/*.xml,classpath*:mapping/*/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
spdata:
  autoconfig:
    enable: false